name: Run and create artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup_python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          python CardGenerator.py

      - name: Upload result as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-zip
          path: BSP_Cards.zip

