name: Run and create artifact
permissions:
  contents: write
on:
  schedule:
    - cron: '0 0 * * *' # run daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          python CardGenerator.py

      - name: Upload result as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: BSP-Cards
          path: BSP_Cards.zip

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          name: Release
          tag_name: v1
          files: BSP_Cards.zip
        

